---

- name: Change file permission /var/log/
  find:
    paths: /var/log/
    file_type: file
    patterns: "*.log*,*log,rhsm/*.log,*"
    recurse: yes
  register: filelist

- name: change permissions
  file:
    path: "{{ item.path }}"
    state: file
    mode: "0600"
  with_items: "{{ filelist.files }}"

