---
- block:
  -  name: Adding tmpfs in /etc/fstab  #Contol ID 14609
     blockinfile:
       path: /etc/fstab
       block: |
         tmpfs       /dev/shm      tmpfs   rw,nosuid,noexec,nodev,seclabel    0 0
       backup: yes
     notify:
       - Mounting tmpfs

  -  name: Adding mount options in /tmp  #Control ID 14599,14602,14603
     mount:
       path: /tmp
       src: /dev/mapper/rootvg-tmp_lv
       fstype: xfs
       opts: defaults,nodev,nosuid,noexec
       state: present
     notify:
       - Remounting /tmp

  -  name: Adding mount options in /home  #Control ID 14601
     mount:
       path: /home
       src: /dev/mapper/rootvg-home_lv
       fstype: xfs
       opts: defaults,nodev
       state: present
     notify:
       - Remounting /home
