---

- name: Fixing permission issues
  file:
    path: '{{item.Path}}'
    mode: '{{item.Perm}}'
    group: '{{item.user}}'
    state: '{{item.State}}'
  with_items:
   - { Path: '/etc/crontab', Perm: '600', user: 'root', State: 'file' }                              			   #Control ID 5154
   - { Path: '/etc/cron.d', Perm: '700', user: 'root', State: 'directory' }                                        #Control ID 7339
   - { Path: '/etc/cron.daily', Perm: '700', user: 'root', State: 'directory' }                                    #Control ID 7341
   - { Path: '/etc/cron.hourly', Perm: '700', user: 'root', State: 'directory' }                                   #Control ID 7343
   - { Path: '/etc/cron.weekly', Perm: '700', user: 'root', State: 'directory' }                                   #Control ID 7345
   - { Path: '/etc/cron.monthly', Perm: '700', user: 'root', State: 'directory' }                                  #Control ID 7347
   - { Path: '/boot/grub2/grub.cfg', Perm: '600', user: 'root', State: 'file' }                                    #Control ID 9340
   - { Path: '/etc/ssh/ssh_host_ecdsa_key', Perm: '600', user: 'root', State: 'file' }               			   #Control ID 11705
   - { Path: '/etc/ssh/ssh_host_ed25519_key', Perm: '600', user: 'root', State: 'file' }             			   #Control ID 11705
   - { Path: '/etc/ssh/ssh_host_rsa_key', Perm: '600', user: 'root', State: 'file' }                 			   #Control ID 11705
