---

- name: Including sub tasks
  block:
    - include: login_defs.yml
    - include: misc.yml
    - include: sshd.yml
    - include: permission.yml
    - include: sysctl.yml
    - include: logfiles.yml
    - include: modprobe.yml
    - include: mounts.yml
    - include: banner.yml
    - include: pwquality.yml
  ignore_errors: yes

