---

###########################################################################################################################################################
#
# Ansible Playbook for applying Qulays Hardening Parameters on RHEL 8.4
#
###########################################################################################################################################################
#
# Author : Rashmi Gupta
#
# Version : 1.0
###########################################################################################################################################################


- hosts: all
  become: True
  become_user: root
  gather_facts: yes

  roles:
   - OS-Hardening-OBSMASTER84
