---

###########################################################################################################################################################
#
# Ansible Playbook for applying Qulays Hardening Parameters on SLES15SP3
#
###########################################################################################################################################################
#
# Author : Rashmi Gupta
#
# Version : 1.0
###########################################################################################################################################################


- hosts: all
  become: True
  become_user: root
  gather_facts: yes

  roles:
   - Qualys-remediation
